export const courseData = [
  {
    id: 1,
    title: "Mastering Graphic Design with Canva",
    slug: "mastering-graphic-design-canva-1",
    lessons: 18,
    duration: "9 hr",
    rating: 4.9,
    reviews: 99,
    category: "Design",
    isBestseller: true,
    type: "video",
    completed: 15,
    description:
      "Learn how to create stunning designs, social media graphics, and marketing materials using Canva’s powerful tools.",
    instructor: "Emma Roberts",
  },
  {
    id: 2,
    title: "JavaScript Essentials",
    slug: "javascript-essentials",
    lessons: 25,
    duration: "10 hr",
    rating: 4.8,
    reviews: 75,
    category: "Development",
    isBestseller: false,
    type: "video",
    completed: 16,
    description:
      "Master the fundamentals of JavaScript, from variables and functions to DOM manipulation and modern ES6 features.",
    instructor: "James Anderson",
  },
  {
    id: 3,
    title: "Intro to Digital Marketing",
    slug: "digital-marketing-intro",
    lessons: 15,
    duration: "5 hr",
    rating: 4.7,
    reviews: 60,
    category: "Marketing",
    isBestseller: false,
    type: "docs",
    completed: 10,
    description:
      "Get a complete introduction to digital marketing strategies, including SEO, email campaigns, and social media tactics.",
    instructor: "Sophia Mitchell",
  },
  {
    id: 4,
    title: "Figma UI Prototyping",
    slug: "figma-ui-prototyping",
    lessons: 12,
    duration: "4 hr",
    rating: 4.9,
    reviews: 88,
    category: "Design",
    isBestseller: false,
    type: "video",
    completed: 12,
    description:
      "Learn to design interactive and visually appealing UI prototypes in Figma, perfect for both web and mobile applications.",
    instructor: "Daniel Clark",
  },
  {
    id: 5,
    title: "Python for Data Analysis",
    slug: "python-data-analysis",
    lessons: 30,
    duration: "12 hr",
    rating: 4.6,
    reviews: 102,
    category: "Data Analysis",
    isBestseller: true,
    type: "video",
    completed: 19,
    description:
      "Analyze, clean, and visualize data effectively with Python using Pandas, NumPy, and Matplotlib libraries.",
    instructor: "Olivia Bennett",
  },
  {
    id: 6,
    title: "Machine Learning Basics",
    slug: "ml-basics",
    lessons: 22,
    duration: "8 hr",
    rating: 4.8,
    reviews: 95,
    category: "Artificial Intelligence",
    isBestseller: false,
    type: "docs",
    completed: 18,
    description:
      "Understand the basics of machine learning algorithms, including supervised and unsupervised models.",
    instructor: "Liam Johnson",
  },
  {
    id: 7,
    title: "Advanced CSS Techniques",
    slug: "advanced-css",
    lessons: 20,
    duration: "7 hr",
    rating: 4.7,
    reviews: 85,
    category: "Development",
    isBestseller: false,
    type: "video",
    completed: 14,
    description:
      "Take your CSS skills to the next level with animations, responsive layouts, and CSS Grid/Flexbox mastery.",
    instructor: "Mia Carter",
  },
  {
    id: 8,
    title: "SEO Mastery Guide",
    slug: "seo-mastery",
    lessons: 18,
    duration: "6 hr",
    rating: 4.5,
    reviews: 78,
    category: "Marketing",
    isBestseller: false,
    type: "docs",
    completed: 18,
    description:
      "Boost your website ranking with proven SEO strategies, keyword optimization, and backlink building.",
    instructor: "Ethan White",
  },
  {
    id: 9,
    title: "Data Visualization in Tableau",
    slug: "tableau-data-visualization",
    lessons: 14,
    duration: "6 hr",
    rating: 4.6,
    reviews: 80,
    category: "Data Analysis",
    isBestseller: false,
    type: "video",
    completed: 14,
    description:
      "Create insightful and interactive dashboards with Tableau to turn raw data into actionable insights.",
    instructor: "Ava Brooks",
  },
  {
    id: 10,
    title: "Neural Networks Explained",
    slug: "neural-networks-explained",
    lessons: 20,
    duration: "10 hr",
    rating: 4.9,
    reviews: 120,
    category: "Artificial Intelligence",
    isBestseller: true,
    type: "video",
    completed: 13,
    description:
      "Dive into the fundamentals of neural networks, deep learning, and how machines learn from data.",
    instructor: "Noah Harris",
  },
  {
    id: 11,
    title: "Typography in Web Design",
    slug: "typography-web-design",
    lessons: 10,
    duration: "3 hr",
    rating: 4.4,
    reviews: 45,
    category: "Design",
    isBestseller: false,
    type: "docs",
    completed: 8,
    description:
      "Learn how to use typography effectively to enhance user experience and create visually stunning websites.",
    instructor: "Grace Foster",
  },
  {
    id: 12,
    title: "React.js Crash Course",
    slug: "reactjs-crash-course",
    lessons: 24,
    duration: "8 hr",
    rating: 4.8,
    reviews: 110,
    category: "Development",
    isBestseller: true,
    type: "video",
    completed: 12,
    description:
      "Quickly get up to speed with React.js by building dynamic, component-based web applications.",
    instructor: "Lucas Parker",
  },
  {
    id: 13,
    title: "Social Media Strategy for Brands",
    slug: "social-media-strategy",
    lessons: 16,
    duration: "5 hr",
    rating: 4.5,
    reviews: 67,
    category: "Marketing",
    isBestseller: false,
    type: "docs",
    completed: 16,
    description:
      "Learn how to create, manage, and optimize social media campaigns that grow brand awareness and engagement.",
    instructor: "Chloe Reed",
  },
];

export const courseCategoryData = [
  "All",
  "Design",
  "Development",
  "Marketing",
  "Data Analysis",
  "Artificial Intelligence",
];

export const testimonialsData = [
  {
    id: 1,
    text: "I had no background in this subject, but the instructor explained everything step by step. I didn't feel overwhelmed at all.",
    name: "Rafiq Ajgar",
    role: "Content Strategist",
  },
  {
    id: 2,
    text: "The hands-on projects and real-world examples made learning fun and effective. I now feel confident applying for higher roles.",
    name: "Sarah Roots",
    role: "User Experience Designer",
  },
  {
    id: 3,
    text: "Course quality was top-notch, and getting lifetime access means I can always come back and review. Highly recommended!",
    name: "Nabila Harsh",
    role: "Marketing Specialist",
  },
];

export const statisticsData = [
  {
    number: "45+",
    label: "Total Tutorials",
  },
  {
    number: "700+",
    label: "Hour Tutorials",
  },
  {
    number: "99%",
    label: "Satisfaction Rate",
  },
];

export const reviewData = [
  {
    id: "1",
    text: "The lessons are clear and easy to follow. I had zero design experience before, and now I feel confident using Figma and building clean UIs.",
    rating: 4.9,
    date: "May 12, 2025",
    author: "Sarah Clack",
  },
  {
    id: "2",
    text: "Great pacing and examples. I finally understand design systems!",
    rating: 4.7,
    date: "May 15, 2025",
    author: "Jordan Blake",
  },
  {
    id: "3",
    text: "The instructor explains concepts in a very intuitive way. Perfect for beginners.",
    rating: 5.0,
    date: "May 18, 2025",
    author: "Anika Patel",
  },
  {
    id: "4",
    text: "I enjoyed the quizzes and projects. The course is hands-on and practical.",
    rating: 4.8,
    date: "May 20, 2025",
    author: "David Zhang",
  },
  {
    id: "5",
    text: "A few parts were fast-paced but overall it’s a great course with clear goals.",
    rating: 4.6,
    date: "May 22, 2025",
    author: "Emily Tran",
  },
  {
    id: "6",
    text: "I loved this course! I'm already using Figma for my startup projects.",
    rating: 4.9,
    date: "May 25, 2025",
    author: "Ravi Deshmukh",
  },
];
