export const courseData = [
  {
    id: "1",
    title: "Mastering Graphic Design with Canva",
    slug: "mastering-graphic-design-canva-1",
    courseContexts: [
      {
        id: "1",
        title: "Introduction to Canva",
        isOpen: true,
        items: [
          {
            id: "1-1",
            title: "Overview of Canva Interface",
            type: "video",
            duration: "04:20 minutes",
          },
          {
            id: "1-2",
            title: "Setting Up Your First Project",
            type: "video",
            duration: "05:10 minutes",
          },
          {
            id: "1-3",
            title: "Basic Tools and Features",
            type: "video",
            duration: "06:15 minutes",
          },
          {
            id: "1-4",
            title: "Quiz: Canva Basics",
            type: "quiz",
            duration: "Test your Canva fundamentals",
          },
        ],
      },
      {
        id: "2",
        title: "Typography & Colors",
        isOpen: false,
        items: [
          {
            id: "2-1",
            title: "Choosing the Right Fonts",
            type: "video",
            duration: "05:30 minutes",
          },
          {
            id: "2-2",
            title: "Color Psychology in Design",
            type: "video",
            duration: "07:40 minutes",
          },
          {
            id: "2-3",
            title: "Practical Typography Tips",
            type: "video",
            duration: "06:05 minutes",
          },
        ],
      },
      {
        id: "3",
        title: "Working with Images",
        isOpen: false,
        items: [
          {
            id: "3-1",
            title: "Uploading and Editing Photos",
            type: "video",
            duration: "06:45 minutes",
          },
          {
            id: "3-2",
            title: "Using Canva’s Stock Library",
            type: "video",
            duration: "05:15 minutes",
          },
        ],
      },
      {
        id: "4",
        title: "Social Media Designs",
        isOpen: false,
        items: [
          {
            id: "4-1",
            title: "Creating Instagram Posts",
            type: "video",
            duration: "08:20 minutes",
          },
          {
            id: "4-2",
            title: "Designing Facebook Banners",
            type: "video",
            duration: "07:05 minutes",
          },
        ],
      },
      {
        id: "5",
        title: "Advanced Features",
        isOpen: false,
        items: [
          {
            id: "5-1",
            title: "Animations and Video Editing",
            type: "video",
            duration: "09:10 minutes",
          },
          {
            id: "5-2",
            title: "Brand Kits & Templates",
            type: "video",
            duration: "06:50 minutes",
          },
        ],
      },
      {
        id: "6",
        title: "Real-World Project",
        isOpen: false,
        items: [
          {
            id: "6-1",
            title: "Design a Marketing Poster",
            type: "video",
            duration: "10:00 minutes",
          },
          {
            id: "6-2",
            title: "Peer Review & Feedback",
            type: "video",
            duration: "06:00 minutes",
          },
        ],
      },
      {
        id: "7",
        title: "Final Wrap-up",
        isOpen: false,
        items: [
          {
            id: "7-1",
            title: "Exporting and Sharing Designs",
            type: "video",
            duration: "05:20 minutes",
          },
          {
            id: "7-2",
            title: "Final Quiz",
            type: "quiz",
            duration: "Check your overall knowledge",
          },
        ],
      },
    ],
    lessons: 18,
    duration: "9 hr",
    rating: 4.9,
    category: "Design",
    isBestseller: true,
    type: "video",
    isMicroLearning: true,
    completed: 15,
    description:
      "Learn how to create stunning designs, social media graphics, and marketing materials using Canva’s powerful tools.",
  },
  {
    id: "2",
    title: "JavaScript Essentials",
    slug: "javascript-essentials",
    courseContexts: [
      {
        id: "1",
        title: "Getting Started",
        isOpen: true,
        items: [
          {
            id: "1-1",
            title: "What is JavaScript?",
            type: "video",
            duration: "05:00 minutes",
          },
          {
            id: "1-2",
            title: "Setting Up Your Environment",
            type: "video",
            duration: "06:15 minutes",
          },
          {
            id: "1-3",
            title: "First JS Program",
            type: "quiz",
            duration:
              "5 questions to test your understanding of JavaScript basics.",
          },
        ],
      },
      {
        id: "2",
        title: "Variables & Data Types",
        isOpen: false,
        items: [
          {
            id: "2-1",
            title: "Understanding Variables",
            type: "video",
            duration: "06:00 minutes",
          },
          {
            id: "2-2",
            title: "Primitive Data Types",
            type: "quiz",
            duration: "4-question quiz on variable types and memory concepts.",
          },
        ],
      },
      {
        id: "3",
        title: "Functions",
        isOpen: false,
        items: [
          {
            id: "3-1",
            title: "Defining Functions",
            type: "video",
            duration: "05:50 minutes",
          },
          {
            id: "3-2",
            title: "Function Parameters",
            type: "video",
            duration: "06:15 minutes",
          },
          {
            id: "3-3",
            title: "Function Quiz",
            type: "quiz",
            duration: "3 tricky questions on parameters and return values.",
          },
        ],
      },
      {
        id: "4",
        title: "Control Flow",
        isOpen: false,
        items: [
          {
            id: "4-1",
            title: "If Statements",
            type: "video",
            duration: "05:40 minutes",
          },
          {
            id: "4-2",
            title: "Loops in JavaScript",
            type: "quiz",
            duration: "Test your loop skills with 5 problems.",
          },
        ],
      },
      {
        id: "5",
        title: "DOM Manipulation",
        isOpen: false,
        items: [
          {
            id: "5-1",
            title: "Selecting Elements",
            type: "video",
            duration: "07:00 minutes",
          },
          {
            id: "5-2",
            title: "Event Listeners",
            type: "video",
            duration: "08:10 minutes",
          },
          {
            id: "5-3",
            title: "DOM Quiz",
            type: "quiz",
            duration: "5 questions to check your DOM manipulation knowledge.",
          },
        ],
      },
      {
        id: "6",
        title: "ES6 Features",
        isOpen: false,
        items: [
          {
            id: "6-1",
            title: "Arrow Functions",
            type: "video",
            duration: "05:45 minutes",
          },
          {
            id: "6-2",
            title: "Template Literals",
            type: "quiz",
            duration: "Short quiz on ES6 syntax and features.",
          },
        ],
      },
      {
        id: "7",
        title: "Final Project",
        isOpen: false,
        items: [
          {
            id: "7-1",
            title: "Building a To-Do App",
            type: "video",
            duration: "10:00 minutes",
          },
          {
            id: "7-2",
            title: "Review & Summary",
            type: "quiz",
            duration: "Final assessment for the course.",
          },
        ],
      },
    ],
    lessons: 25,
    duration: "10 hr",
    rating: 4.8,
    category: "Development",
    isBestseller: false,
    type: "video",
    isMicroLearning: true,
    completed: 16,
    description:
      "Master the fundamentals of JavaScript, from variables and functions to DOM manipulation and modern ES6 features.",
  },
  {
    id: "3",
    title: "React.js for Beginners",
    slug: "reactjs-for-beginners",
    courseContexts: [
      {
        id: "1",
        title: "Introduction to React",
        isOpen: true,
        items: [
          {
            id: "1-1",
            title: "What is React?",
            type: "video",
            duration: "05:20 minutes",
          },
          {
            id: "1-2",
            title: "Setting up React Environment",
            type: "video",
            duration: "06:40 minutes",
          },
        ],
      },
      {
        id: "2",
        title: "JSX & Components",
        isOpen: false,
        items: [
          {
            id: "2-1",
            title: "JSX Basics",
            type: "video",
            duration: "07:15 minutes",
          },
          {
            id: "2-2",
            title: "Functional vs Class Components",
            type: "video",
            duration: "06:30 minutes",
          },
        ],
      },
      {
        id: "3",
        title: "State & Props",
        isOpen: false,
        items: [
          {
            id: "3-1",
            title: "Managing State",
            type: "video",
            duration: "07:50 minutes",
          },
          {
            id: "3-2",
            title: "Passing Props",
            type: "video",
            duration: "06:10 minutes",
          },
        ],
      },
      {
        id: "4",
        title: "Event Handling",
        isOpen: false,
        items: [
          {
            id: "4-1",
            title: "Handling Click Events",
            type: "video",
            duration: "06:05 minutes",
          },
          {
            id: "4-2",
            title: "Form Inputs in React",
            type: "video",
            duration: "07:00 minutes",
          },
        ],
      },
      {
        id: "5",
        title: "Conditional Rendering",
        isOpen: false,
        items: [
          {
            id: "5-1",
            title: "Rendering with If Statements",
            type: "video",
            duration: "05:40 minutes",
          },
          {
            id: "5-2",
            title: "Ternary Operator in JSX",
            type: "video",
            duration: "05:25 minutes",
          },
        ],
      },
      {
        id: "6",
        title: "Lists & Keys",
        isOpen: false,
        items: [
          {
            id: "6-1",
            title: "Rendering Lists",
            type: "video",
            duration: "06:00 minutes",
          },
          {
            id: "6-2",
            title: "Unique Keys in Lists",
            type: "video",
            duration: "05:30 minutes",
          },
        ],
      },
      {
        id: "7",
        title: "Final Project",
        isOpen: false,
        items: [
          {
            id: "7-1",
            title: "Building a Counter App",
            type: "video",
            duration: "09:00 minutes",
          },
          {
            id: "7-2",
            title: "Course Recap",
            type: "video",
            duration: "04:50 minutes",
          },
        ],
      },
    ],
    lessons: 20,
    duration: "8 hr",
    rating: 4.7,
    category: "Development",
    isBestseller: true,
    type: "docs",
    isMicroLearning: false,
    completed: 20,
    description:
      "Learn the fundamentals of React.js and build interactive user interfaces from scratch.",
  },
  {
    id: "4",
    title: "UI/UX Design Fundamentals",
    slug: "ui-ux-design-fundamentals",
    courseContexts: [
      {
        id: "1",
        title: "Introduction to UI/UX",
        isOpen: true,
        items: [
          {
            id: "1-1",
            title: "Understanding UI and UX",
            type: "video",
            duration: "05:30 minutes",
          },
          {
            id: "1-2",
            title: "Why UI/UX Matters",
            type: "video",
            duration: "06:20 minutes",
          },
        ],
      },
      {
        id: "2",
        title: "Principles of Design",
        isOpen: false,
        items: [
          {
            id: "2-1",
            title: "Color Theory",
            type: "video",
            duration: "07:00 minutes",
          },
          {
            id: "2-2",
            title: "Typography Basics",
            type: "video",
            duration: "06:45 minutes",
          },
        ],
      },
      {
        id: "3",
        title: "Wireframing",
        isOpen: false,
        items: [
          {
            id: "3-1",
            title: "Low Fidelity Wireframes",
            type: "video",
            duration: "07:15 minutes",
          },
          {
            id: "3-2",
            title: "High Fidelity Wireframes",
            type: "video",
            duration: "07:50 minutes",
          },
        ],
      },
      {
        id: "4",
        title: "Prototyping",
        isOpen: false,
        items: [
          {
            id: "4-1",
            title: "Creating Interactive Prototypes",
            type: "video",
            duration: "08:20 minutes",
          },
          {
            id: "4-2",
            title: "User Testing",
            type: "video",
            duration: "06:35 minutes",
          },
        ],
      },
      {
        id: "5",
        title: "Accessibility",
        isOpen: false,
        items: [
          {
            id: "5-1",
            title: "Designing for All Users",
            type: "video",
            duration: "06:50 minutes",
          },
          {
            id: "5-2",
            title: "Accessibility Tools",
            type: "video",
            duration: "05:40 minutes",
          },
        ],
      },
      {
        id: "6",
        title: "Case Study",
        isOpen: false,
        items: [
          {
            id: "6-1",
            title: "Real World UI/UX Example",
            type: "video",
            duration: "08:15 minutes",
          },
        ],
      },
    ],
    lessons: 16,
    duration: "7 hr",
    rating: 4.8,
    category: "Design",
    isBestseller: false,
    type: "video",
    isMicroLearning: false,
    completed: 10,
    description:
      "A beginner-friendly guide to designing beautiful, user-centered interfaces.",
  },
  {
    id: "5",
    title: "Python Programming for Beginners",
    slug: "python-programming-beginners",
    courseContexts: [
      {
        id: "1",
        title: "Introduction to Python",
        isOpen: true,
        items: [
          {
            id: "1-1",
            title: "Why Python?",
            type: "video",
            duration: "04:55 minutes",
          },
          {
            id: "1-2",
            title: "Installing Python",
            type: "video",
            duration: "05:30 minutes",
          },
        ],
      },
      {
        id: "2",
        title: "Variables & Data Types",
        isOpen: false,
        items: [
          {
            id: "2-1",
            title: "Numbers & Strings",
            type: "video",
            duration: "06:15 minutes",
          },
          {
            id: "2-2",
            title: "Lists & Dictionaries",
            type: "video",
            duration: "07:10 minutes",
          },
        ],
      },
      {
        id: "3",
        title: "Control Structures",
        isOpen: false,
        items: [
          {
            id: "3-1",
            title: "If Statements",
            type: "video",
            duration: "05:40 minutes",
          },
          {
            id: "3-2",
            title: "Loops",
            type: "video",
            duration: "06:30 minutes",
          },
        ],
      },
      {
        id: "4",
        title: "Functions",
        isOpen: false,
        items: [
          {
            id: "4-1",
            title: "Defining Functions",
            type: "video",
            duration: "06:05 minutes",
          },
          {
            id: "4-2",
            title: "Function Parameters",
            type: "video",
            duration: "06:25 minutes",
          },
        ],
      },
      {
        id: "5",
        title: "Modules & Packages",
        isOpen: false,
        items: [
          {
            id: "5-1",
            title: "Importing Modules",
            type: "video",
            duration: "05:50 minutes",
          },
          {
            id: "5-2",
            title: "Using pip",
            type: "video",
            duration: "06:20 minutes",
          },
        ],
      },
    ],
    lessons: 14,
    duration: "6 hr",
    rating: 4.9,
    category: "Programming",
    isBestseller: true,
    type: "docs",
    isMicroLearning: false,
    completed: 9,
    description:
      "Learn Python programming from scratch and start your coding journey.",
  },
  {
    id: "6",
    title: "Digital Marketing Basics",
    slug: "digital-marketing-basics",
    courseContexts: [
      {
        id: "1",
        title: "Introduction to Digital Marketing",
        isOpen: true,
        items: [
          {
            id: "1-1",
            title: "What is Digital Marketing?",
            type: "video",
            duration: "05:40 minutes",
          },
          {
            id: "1-2",
            title: "Digital vs Traditional Marketing",
            type: "video",
            duration: "06:10 minutes",
          },
        ],
      },
      {
        id: "2",
        title: "SEO Basics",
        isOpen: false,
        items: [
          {
            id: "2-1",
            title: "On-page SEO",
            type: "video",
            duration: "07:20 minutes",
          },
          {
            id: "2-2",
            title: "Off-page SEO",
            type: "video",
            duration: "06:55 minutes",
          },
        ],
      },
      {
        id: "3",
        title: "Social Media Marketing",
        isOpen: false,
        items: [
          {
            id: "3-1",
            title: "Facebook Marketing",
            type: "video",
            duration: "07:00 minutes",
          },
          {
            id: "3-2",
            title: "Instagram Marketing",
            type: "video",
            duration: "06:40 minutes",
          },
        ],
      },
      {
        id: "4",
        title: "Email Marketing",
        isOpen: false,
        items: [
          {
            id: "4-1",
            title: "Building Email Lists",
            type: "video",
            duration: "06:15 minutes",
          },
          {
            id: "4-2",
            title: "Crafting Campaigns",
            type: "video",
            duration: "07:05 minutes",
          },
        ],
      },
    ],
    lessons: 12,
    duration: "5 hr",
    rating: 4.6,
    category: "Marketing",
    isBestseller: false,
    type: "video",
    isMicroLearning: false,
    completed: 12,
    description:
      "A beginner’s guide to promoting products and services in the digital space.",
  },
  {
    id: "7",
    title: "Photography Masterclass",
    slug: "photography-masterclass",
    courseContexts: [
      {
        id: "1",
        title: "Camera Basics",
        isOpen: true,
        items: [
          {
            id: "1-1",
            title: "Understanding Your Camera",
            type: "video",
            duration: "06:30 minutes",
          },
          {
            id: "1-2",
            title: "Camera Settings",
            type: "video",
            duration: "07:15 minutes",
          },
        ],
      },
      {
        id: "2",
        title: "Composition Techniques",
        isOpen: false,
        items: [
          {
            id: "2-1",
            title: "Rule of Thirds",
            type: "video",
            duration: "05:40 minutes",
          },
          {
            id: "2-2",
            title: "Leading Lines",
            type: "video",
            duration: "06:25 minutes",
          },
        ],
      },
      {
        id: "3",
        title: "Lighting",
        isOpen: false,
        items: [
          {
            id: "3-1",
            title: "Natural Light",
            type: "video",
            duration: "07:20 minutes",
          },
          {
            id: "3-2",
            title: "Artificial Light",
            type: "video",
            duration: "06:50 minutes",
          },
        ],
      },
      {
        id: "4",
        title: "Editing Photos",
        isOpen: false,
        items: [
          {
            id: "4-1",
            title: "Using Lightroom",
            type: "video",
            duration: "07:10 minutes",
          },
          {
            id: "4-2",
            title: "Basic Photoshop Edits",
            type: "video",
            duration: "06:40 minutes",
          },
        ],
      },
    ],
    lessons: 14,
    duration: "6 hr",
    rating: 4.8,
    category: "Photography",
    isBestseller: true,
    type: "docs",
    isMicroLearning: false,
    completed: 11,
    description:
      "A complete photography course to help you capture stunning images.",
  },
];





export const notificationsData = [
  {
    id: "1",
    message: "New course React Basics has been added.",
    time: new Date("2025-08-17T10:00:00Z"),
  },
  {
    id: "2",
    message: "Your progress in Next.js Advanced is 70%.",
    time: new Date("2025-08-16T11:30:00Z"),
  },
  {
    id: "3",
    message: "Instructor replied to your review.",
    time: new Date("2025-08-14T15:45:00Z"),
  },
];

export const courseCategoryData = [
  "All",
  "Design",
  "Development",
  "Marketing",
  "Data Analysis",
  "Artificial Intelligence",
];

export const testimonialsData = [
  {
    id: "1",
    text: "I had no background in this subject, but the instructor explained everything step by step. I didn't feel overwhelmed at all.",
    name: "Rafiq Ajgar",
    role: "Content Strategist",
    rating: 4
  },
  {
    id: "2",
    text: "The hands-on projects and real-world examples made learning fun and effective. I now feel confident applying for higher roles.",
    name: "Sarah Roots",
    role: "User Experience Designer",
    rating: 5
  },
  {
    id: "3",
    text: "Course quality was top-notch, and getting lifetime access means I can always come back and review. Highly recommended!",
    name: "Nabila Harsh",
    role: "Marketing Specialist",
    rating: 3
  },
];

export const statisticsData = [
  {
    number: "45+",
    label: "Total Tutorials",
  },
  {
    number: "700+",
    label: "Hour Tutorials",
  },
  {
    number: "99%",
    label: "Satisfaction Rate",
  },
];

export const reviewData = [
  {
    id: "1",
    courseId: "1",
    text: "The lessons are clear and easy to follow. I had zero design experience before, and now I feel confident using Figma and building clean UIs.",
    rating: 4.9,
    date: "May 12, 2025",
    author: "Sarah Clack",
  },
  {
    id: "2",
    courseId: "1",
    text: "Amazing course! I love the practical exercises.",
    rating: 5.0,
    date: "May 14, 2025",
    author: "Emily Tran",
  },
  {
    id: "3",
    courseId: "1",
    text: "Well-structured and easy to follow lessons.",
    rating: 4.8,
    date: "May 16, 2025",
    author: "Ravi Deshmukh",
  },
  {
    id: "4",
    courseId: "2",
    text: "Great pacing and examples. I finally understand JavaScript better!",
    rating: 4.7,
    date: "May 15, 2025",
    author: "Jordan Blake",
  },
  {
    id: "5",
    courseId: "2",
    text: "JavaScript concepts were explained clearly.",
    rating: 4.6,
    date: "May 17, 2025",
    author: "Liam Green",
  },
  {
    id: "6",
    courseId: "2",
    text: "Good intro course, helped me get started fast.",
    rating: 4.5,
    date: "May 19, 2025",
    author: "Sophia Young",
  },
  {
    id: "7",
    courseId: "2",
    text: "Loved the exercises and real-world examples.",
    rating: 4.8,
    date: "May 21, 2025",
    author: "Kevin Lee",
  },
  {
    id: "8",
    courseId: "3",
    text: "Digital marketing basics were covered really well.",
    rating: 4.8,
    date: "May 20, 2025",
    author: "David Zhang",
  },
  {
    id: "9",
    courseId: "3",
    text: "I learned a lot about SEO and email campaigns.",
    rating: 4.7,
    date: "May 22, 2025",
    author: "Priya Kaur",
  },
  {
    id: "10",
    courseId: "3",
    text: "Perfect for beginners with actionable advice.",
    rating: 4.6,
    date: "May 23, 2025",
    author: "Ethan Scott",
  },
  {
    id: "11",
    courseId: "4",
    text: "Excellent Figma techniques taught step-by-step.",
    rating: 4.8,
    date: "May 26, 2025",
    author: "Jessica Lee",
  },
  {
    id: "12",
    courseId: "4",
    text: "Very practical and useful for UI design.",
    rating: 4.9,
    date: "May 28, 2025",
    author: "Mark Thompson",
  },
  {
    id: "13",
    courseId: "4",
    text: "I feel confident prototyping after this course.",
    rating: 5.0,
    date: "May 29, 2025",
    author: "Amelia White",
  },
  {
    id: "14",
    courseId: "5",
    text: "Python for data analysis was clear and detailed.",
    rating: 4.7,
    date: "May 27, 2025",
    author: "Olivia Bennett",
  },
  {
    id: "15",
    courseId: "5",
    text: "Great examples on data visualization.",
    rating: 4.8,
    date: "May 30, 2025",
    author: "James Brown",
  },
  {
    id: "16",
    courseId: "5",
    text: "Helped me understand Pandas and NumPy easily.",
    rating: 4.9,
    date: "June 1, 2025",
    author: "Mia Carter",
  },
  {
    id: "17",
    courseId: "5",
    text: "Loved the practical projects, very helpful.",
    rating: 4.7,
    date: "June 3, 2025",
    author: "Ethan Wright",
  },
  {
    id: "18",
    courseId: "6",
    text: "The ML basics course made complex topics simple.",
    rating: 4.8,
    date: "May 28, 2025",
    author: "Liam Johnson",
  },
  {
    id: "19",
    courseId: "6",
    text: "Great intro to supervised and unsupervised learning.",
    rating: 4.7,
    date: "May 30, 2025",
    author: "Nina Patel",
  },
  {
    id: "20",
    courseId: "6",
    text: "The concepts are clear and well-explained.",
    rating: 4.9,
    date: "June 2, 2025",
    author: "Carlos Diaz",
  },
  {
    id: "21",
    courseId: "7",
    text: "Advanced CSS concepts really boosted my skills.",
    rating: 4.7,
    date: "June 1, 2025",
    author: "Mia Carter",
  },
  {
    id: "22",
    courseId: "7",
    text: "Loved the animations and Flexbox examples.",
    rating: 4.8,
    date: "June 3, 2025",
    author: "Sophia Miller",
  },
  {
    id: "23",
    courseId: "7",
    text: "Very practical course with useful tips.",
    rating: 4.6,
    date: "June 5, 2025",
    author: "James Parker",
  },
  {
    id: "24",
    courseId: "8",
    text: "SEO strategies here helped my site traffic grow.",
    rating: 4.5,
    date: "June 4, 2025",
    author: "Ethan White",
  },
  {
    id: "25",
    courseId: "8",
    text: "Good insights on keyword optimization.",
    rating: 4.6,
    date: "June 6, 2025",
    author: "Anna Kim",
  },
  {
    id: "26",
    courseId: "8",
    text: "The backlink building section was very useful.",
    rating: 4.7,
    date: "June 7, 2025",
    author: "Mark Wilson",
  },
  {
    id: "27",
    courseId: "9",
    text: "Tableau dashboards are so much easier after this course.",
    rating: 4.6,
    date: "June 5, 2025",
    author: "Ava Brooks",
  },
  {
    id: "28",
    courseId: "9",
    text: "Loved the hands-on data visualization projects.",
    rating: 4.8,
    date: "June 7, 2025",
    author: "Olivia Evans",
  },
  {
    id: "29",
    courseId: "9",
    text: "Great course for beginners to Tableau.",
    rating: 4.7,
    date: "June 8, 2025",
    author: "Michael Green",
  },
  {
    id: "30",
    courseId: "10",
    text: "Neural networks explained simply and clearly.",
    rating: 4.9,
    date: "June 6, 2025",
    author: "Noah Harris",
  },
  {
    id: "31",
    courseId: "10",
    text: "Deep learning fundamentals are well covered.",
    rating: 5.0,
    date: "June 8, 2025",
    author: "Sophia Bennett",
  },
  {
    id: "32",
    courseId: "10",
    text: "This course gave me a solid foundation in neural networks.",
    rating: 4.8,
    date: "June 10, 2025",
    author: "David Clark",
  },
  {
    id: "33",
    courseId: "10",
    text: "Highly recommend for anyone starting in AI.",
    rating: 4.9,
    date: "June 12, 2025",
    author: "Emma Foster",
  },
  {
    id: "34",
    courseId: "11",
    text: "Typography tips really improved my web designs.",
    rating: 4.4,
    date: "June 9, 2025",
    author: "Grace Foster",
  },
  {
    id: "35",
    courseId: "11",
    text: "Clear explanations and practical advice.",
    rating: 4.5,
    date: "June 10, 2025",
    author: "Hannah Scott",
  },
  {
    id: "36",
    courseId: "11",
    text: "A great course for improving design aesthetics.",
    rating: 4.6,
    date: "June 12, 2025",
    author: "Jack Wilson",
  },
  {
    id: "37",
    courseId: "12",
    text: "React.js crash course was fast-paced but comprehensive.",
    rating: 4.8,
    date: "June 11, 2025",
    author: "Lucas Parker",
  },
  {
    id: "38",
    courseId: "12",
    text: "Good practical examples with hooks and components.",
    rating: 4.7,
    date: "June 13, 2025",
    author: "Zoe Adams",
  },
  {
    id: "39",
    courseId: "12",
    text: "Helped me understand React quickly and clearly.",
    rating: 4.9,
    date: "June 15, 2025",
    author: "Oliver King",
  },
  {
    id: "40",
    courseId: "13",
    text: "Social media strategies were easy to apply.",
    rating: 4.5,
    date: "June 14, 2025",
    author: "Chloe Reed",
  },
  {
    id: "41",
    courseId: "13",
    text: "Great insights on brand engagement.",
    rating: 4.6,
    date: "June 16, 2025",
    author: "Ella Brooks",
  },
  {
    id: "42",
    courseId: "13",
    text: "Loved the campaign management tips.",
    rating: 4.7,
    date: "June 18, 2025",
    author: "Mason Hill",
  },
];
